name: Discord Notify

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🚀 New push: ${{ github.event.head_commit.message }}\"}" \
          ${{ https://discord.com/api/webhooks/1494176278260224081/X968pdy3gZQKRb3hpg3_ESZRwGOmS8XNwrbqaJI4inC8pLycCHGL5xLcjrJHzbyEYm2y }}